# Generated by Django 4.1.7 on 2023-03-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0002_alter_write_create_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="write",
            name="category",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="write",
            name="price",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="write",
            name="tmethod",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="write",
            name="create_date",
            field=models.DateTimeField(),
        ),
    ]
