# Generated by Django 4.1.7 on 2023-03-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0003_write_category_write_price_write_tmethod_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="write",
            name="category",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="write",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="write",
            name="tmethod",
            field=models.TextField(default=""),
        ),
    ]
