# Generated by Django 4.1.7 on 2023-03-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0004_alter_write_category_alter_write_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="write",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
