# Generated by Django 4.1.7 on 2023-03-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0016_answer_category_answer_price_answer_tmethod"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="category",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="price",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="tmethod",
        ),
    ]
