# Generated by Django 4.1.7 on 2023-03-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0019_alter_write_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="write",
            name="images",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
    ]
