# Generated by Django 4.1.7 on 2023-03-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default=None, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phonenumber",
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default=None, max_length=24, null=True),
        ),
    ]
