# Generated by Django 4.1.7 on 2023-03-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_user_address_user_nickname_user_phonenumber_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="date_of_birth",
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True, default=None, max_length=24, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phonenumber",
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, default=None, max_length=24, null=True),
        ),
    ]
